# This is a basic workflow to help you get started with GitHub Actions.
name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  #To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://BadreddineNourhene:$HF@hugging-face.co/spaces/BadreddineNourhene/demo
      - name: Push to Hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://BadreddineNourhene:$HF@hugging-face.co/spaces/BadreddineNourhene/demo main
